app = "thirsty-sword-lesbot"
kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
allowed_public_ports = [ ]
auto_rollback = true

[deploy]
  release_command = "npx prisma migrate deploy"

[processes]
  site = 'npm run start:site'
  bot = 'npm run start:bot'

[[services]]
internal_port = 3000
processes = [ "site" ]
protocol = "tcp"
script_checks = [ ]

  [services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

  [[services.ports]]
  handlers = [ "http" ]
  port = 80
  force_https = true

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443

  [[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"

  [[services.http_checks]]
  interval = "10s"
  grace_period = "5s"
  method = "get"
  path = "/healthcheck"
  protocol = "http"
  timeout = "2s"
  tls_skip_verify = false
  headers = { }
